### ISSUE TITLE
Getting Port using NodePort service

### ISSUE THREAD

**Issue by ccambien** [monostream/helmi#13]
Hi. I create a mariadb database using the bitnami chart for mariadb and asked for a NodePort Service:

Chart values section:

```
chart-values:
  service:
    type: "NodePort"
  db:
    user: "{{ generateUsername }}"
    password: "{{ generatePassword }}"
    name: db
```
The chart is provisionned but how do I get the external Port associated with the nodeport service in the "user-credentials" section ?

Considering the service :

```
$ kubectl get services
NAME                          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
helmi67431aa67a0142-mariadb   NodePort    10.111.222.149   <none>        3306:32542/TCP   60m
```

Thanks

**Comment by gandro** [comment]
Hi there!

You *should* be able to retrieve the mapped port using `{{ .Services.Port "mariadb" 3306 }} `. You can also use the port value from the bitnami chart (e.g. `.Values.service.port`, depends on the chart) instead of hard-coding `3306`. However, I haven't tested NodePort services in a while, let me know if there are any issues.

**Comment by ccambien** [comment]
Thanks for the suggestion. I tried that, but it evaluates to ""

Here is my credentials section:

```
user-credentials:
  uri: "mysql://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ .Cluster.Address }}:{{ .Services.Port "mariadb" 3306 }}/{\
{ .Values.db.name }}"
  jdbcUrl: "jdbc:mysql://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ .Cluster.Address }}:{{ .Services.Port "mariadb" \
3306 }}/{{ .Values.db.name }}?user={{ .Values.db.user }}\u0026password={{ .Values.db.password }}"
  username: "{{ .Values.db.user }}"
  password: "{{ .Values.db.password }}"
  database: "{{ .Values.db.name }}"
  hostname: "{{ .Cluster.Address }}"
  serviceName: "{{ .Release.Name }}-mariadb"
  port: "{{ .Services.Port "mariadb" 3306 }}"
  helmReleaseName: "{{ .Release.Name }}"
  helmNamespace: "{{ .Release.Namespace }}"
  clusterAddress: "{{ .Cluster.Address }}"
  clusterHostname: "{{ .Cluster.Hostname }}"
```

Here's what I obtain:
```

$ eden --url=http://localhost:5000 --client=admin --client-secret=secret  credentials -i mariadb-free-67431aa6-7a01-4237-ac68-f19c8de84237 -b mariadb-38020f9a-2c4c-4883-90cb-4dd5cb3a2d78
{
  "clusterAddress": "192.168.0.3",
  "clusterHostname": "my-instance",
  "database": "db",
  "helmNamespace": "default",
  "helmReleaseName": "helmi67431aa67a0142",
  "hostname": "192.168.0.3",
  "jdbcUrl": "jdbc:mysql://7df57ebada32419198ba9f3856d1847f:c7ae930bd44f448b8ca93c34549f6304@192.168.0.3:/db?user=7df57ebada32419198ba9f3856d1847f\u0026password=c7ae930bd44f448b8ca93c34549f6304",
  "password": "c7ae930bd44f448b8ca93c34549f6304",
  "port": "",
  "serviceName": "helmi67431aa67a0142-mariadb",
  "uri": "mysql://7df57ebada32419198ba9f3856d1847f:c7ae930bd44f448b8ca93c34549f6304@192.168.0.3:/db",
  "username": "7df57ebada32419198ba9f3856d1847f"

```

- What is the second argument for {{ .Services.Port "mariadb" 3306 }} ?
- Do you have other suggestions for exposing the service outside the K8s cluster, instead of using NodePort? I have a cloud foundry platform and and openshift platform and I'd like to consume services from a common, independant K8s cluster.
